// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBULVHStn7K_JyM0mkX-XBvPlacEHo6Ag8',
    appId: '1:642810436386:web:a8b264c6b57098bdf9a37b',
    messagingSenderId: '642810436386',
    projectId: 'tarantulaapp',
    authDomain: 'tarantulaapp.firebaseapp.com',
    databaseURL: 'https://tarantulaapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tarantulaapp.appspot.com',
    measurementId: 'G-YBKQR6EB88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6dspGtDPkXlbmh6AT-E8kslPPmmN7EO0',
    appId: '1:642810436386:android:026022e062898334f9a37b',
    messagingSenderId: '642810436386',
    projectId: 'tarantulaapp',
    databaseURL: 'https://tarantulaapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tarantulaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzpBlWufG6CZi4balTvUFxFi-GJzvId0Y',
    appId: '1:642810436386:ios:988c7c5960504f72f9a37b',
    messagingSenderId: '642810436386',
    projectId: 'tarantulaapp',
    databaseURL: 'https://tarantulaapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tarantulaapp.appspot.com',
    iosClientId: '642810436386-l47iaqactcdt2isfqh3kvdsmn11fq2od.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzpBlWufG6CZi4balTvUFxFi-GJzvId0Y',
    appId: '1:642810436386:ios:988c7c5960504f72f9a37b',
    messagingSenderId: '642810436386',
    projectId: 'tarantulaapp',
    databaseURL: 'https://tarantulaapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tarantulaapp.appspot.com',
    iosClientId: '642810436386-l47iaqactcdt2isfqh3kvdsmn11fq2od.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4',
  );
}
